[project]
name = "client"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "PySide6>=6.6"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["app"]
